# Generated by Django 3.1.3 on 2020-11-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasien', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('umur', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('', '-Pilih-'), ('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='-Pilih-', max_length=200)),
                ('sg', models.FloatField(choices=[('', '-Pilih-'), (1.005, '1.005'), (1.01, '1.010'), (1.015, '1.015'), (1.02, '1.020'), (1.025, '1.025'), (1.02, 'Lainya')], default='-Pilih-')),
                ('al', models.FloatField(choices=[('', '-Pilih-'), (0.0, '0'), (1.0, '1'), (2.0, '2'), (3.0, '3'), (4.0, '4'), (5.0, '5'), (0.0, 'Lainya')], default='-Pilih-')),
                ('hemo', models.FloatField()),
                ('htn', models.FloatField(choices=[('', '-Pilih-'), (1.0, 'Yes'), (0.0, 'No'), (0.0, 'Lainya')], default='-Pilih-')),
                ('dm', models.FloatField(choices=[('', '-Pilih-'), (1.0, 'Yes'), (0.0, 'No'), (0.0, 'Lainya')], default='-Pilih-')),
                ('appet', models.FloatField(choices=[('', '-Pilih-'), (1.0, 'Good'), (0.0, 'Poor'), (1.0, 'Lainya')], default='-Pilih-')),
                ('prediksi', models.CharField(blank=True, editable=False, max_length=200)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
